### ISSUE TITLE
Cyclic Type Checking

### ISSUE THREAD

**Issue by gingerBill** [gingerBill/Odin#1]
At the moment, there is no cyclic type checking and if a type has a cyclical definition, it will cause the compiler to go into an infinite loop.

Examples:
```
A :: type A

B :: type struct {
	c: C;
};

C :: type struct {
	b: B;
};
```

**Comment by ratchetfreak** [comment]
use a stack when you start into creating a type that not concrete yet, then each time you find a type used by value that's also not concrete (size unknown) walk up the stack and check if it is recursing and if not then push the new typ on the stack and finalize it once you are done finalizing pop it off the stack.

That or a loop counter that when it reaches some high enough value (like the total number of struct types visible in that scope) creates an error.

**Comment by gingerBill** [comment]
I've just implement a (crude) cyclic type checking system by calculating the alignment or size of the type and keeping a _path_ of the types. If that type is already in that _path_, an error will be printed of the illegal declaration cycle.

The cyclic checking _should_ be done in the entity declaration stage but this works for now and is simpler to implement.
