### ISSUE TITLE
Accessing members of structs from maps broken.

### ISSUE THREAD

**Issue by vassvik** [gingerBill/Odin#115]
See the snippet below:
```go
import "core:fmt.odin";

Foo :: struct {
	a: int,
}

main :: proc() {
	foos: map[string]Foo;

	foos["hey"] = Foo{1};
	foos["ho"] = Foo{2};
	foos["let's"] = Foo{3};
	foos["go"] = Foo{4};

	for v, s in foos {
		fmt.println(s, v, v.a);
	}

	fmt.println(foos["hey"],   foos["hey"].a);
	fmt.println(foos["ho"],    foos["ho"].a);
	fmt.println(foos["let's"], foos["let's"].a);
	fmt.println(foos["go"],    foos["go"].a);
}
```
Output: 
```go
hey Foo{a = 1} 1
ho Foo{a = 2} 2
let's Foo{a = 3} 3
go Foo{a = 4} 4
Foo{a = 1} 4
Foo{a = 2} 4
Foo{a = 3} 4
Foo{a = 4} 4
```

**Comment by gingerBill** [comment]
With only looking at the code, it seems that selector expressions (x.y) are not being handled correctly for values with addressing modes such as those for maps.

Lines 5214,  5229, and any line that does something of this nature, `ir_build_addr(proc, expr).addr`, should be replaced with a wrapping function which takes into account that expression's addressing mode.
