### ISSUE TITLE
No output on OSX

### ISSUE THREAD

**Issue by clankill3r** [gingerBill/Odin#117]
I can build the compiler fine.
When I run odin it also outputs:

> ./odin is a tool for managing Odin source code
> Usage:
> 	./odin command [arguments]
> Commands:
> 	build        compile .odin file as executable
> 	build_dll    compile .odin file as dll
> 	run          compile and run .odin file
> 	docs         generate documentation for a .odin file
> 	version      print version1
> 

But when I run `./odin run examples/demo.odin` there is no output in the terminal.
This happens on osx.

**Comment by bdoner** [comment]
I think this is the culprit: [demo.odin#L564](https://github.com/gingerBill/Odin/blob/master/examples/demo.odin#L564)

Try checking out a [release](https://github.com/gingerBill/Odin/releases) instead of `master` 😄

**Comment by clankill3r** [comment]
A thanks!

**Comment by zangent** [comment]
Probably don't check out a release like bdoner said, though.
This language moves fast, but the more you lag behind `master`, the harder it will be to fix when the language *does* update.

Even though the demo isn't printing anything (because it's disabled), it's obviously compiling successfully, so you can use Odin from master with no trouble.

(I'm a fellow Mac user, and it works fine!)

**Comment by clankill3r** [comment]
@zangent  Is it possible yet to get an OpenGL window running on OSX?

**Comment by zangent** [comment]
For now (and the foreseeable future), not natively.
That said, you can use SDL or GLFW (both of which I've seen Odin bindings for, but as I'm on my phone, I can't link right now) and then Vassvik wrote an OpenGL loader (like GLEW) that works on all platforms with a bit of coercion

I'll come back later and add links and a small example of how it all works together.

**Comment by vassvik** [comment]
https://github.com/vassvik/odin-glfw
https://github.com/vassvik/odin-gl

The former merely binds to GLFW, while the latter uses glfwGetProcAddress (or any function pointer loader of your choice) to get OpenGL functions from the driver. Both work out of the box in Linux and Windows, but I think might need some framework tinkering to get it to work on MacOS. Then again I could be wrong and it just works.

**Comment by vassvik** [comment]
There's also https://github.com/vassvik/odin-gl_examples, although I will have to see if they are updated

**Comment by zangent** [comment]
`glfwGetProcAddress` works fine on macOS, if you end up using glfw. In fact, when I implemented OpenGL function pointer loading for my game engine (using SDL, so no glfw for me), I checked out the source code of GLFW to see how they did it!
