### ISSUE TITLE
Anonymous Imports

### ISSUE THREAD

**Issue by bpunsky** [gingerBill/Odin#127]
There should be a way to `export` or `using import` a file without creating an identifier. For example, if the name of the file causes a conflict, or there is a name within that file that's the same as the file name. Assuming you never have to manually reference the import, this isn't an issue.

What I've been doing as a hack:
```
using import _0 "shared:remove.odin"
using import _1 "shared:queue.odin"
```

My proposal:
```
using import _ "shared:remove.odin"
using import _ "shared:queue.odin"
```

To illustrate the problem, `remove.odin` has a procedure in it called `remove`, so just `using import`ing it alone causes a naming conflict. `queue.odin` has a `struct`, `Queue`, and it's natural to do `queue: Queue(int);`. This is also problematic.

Apparently I can't tag my own issue as a feature request? Oh well. Sorry. Not a bug.

**Comment by gingerBill** [comment]
Do want this to be the functionality then?
```c
using import _ "foo.odin" // valid
import _ "foo.odin" // invalid
```

**Comment by bpunsky** [comment]
Consistency-wise it makes sense to allow anonymous imports with `import`, but obviously it makes zero sense in practice since you couldn't access the import... maybe allow it and fire a warning? Or just disallow it because it's stupid? ¯\_(ツ)_/¯
