### ISSUE TITLE
Procedure overloading not resolving for ..any

### ISSUE THREAD

**Issue by ThisDrunkDane** [gingerBill/Odin#13]
```
main :: proc() {
    foo("FOO");
    foo("FOO", "FOO");
    foo("FOO", "FOO", "FOO");
}

foo :: proc(test : string, test1 : string, args : ...any) { ... }

foo :: proc(test : string) { ... }
```

This code snippet produces ` No overloads for 'Foo' that match with the given arguments ` on the third `Foo(...)` call

**Comment by gingerBill** [comment]
I've fixed this problem in the latest commit. It was caused by "untyped" constants not checking if they could convert to any (which they should be able to).
