### ISSUE TITLE
Issues with `uintptr` changes`

### ISSUE THREAD

**Issue by bpunsky** [gingerBill/Odin#130]
There are a few issues with `uintptr` and not being able to cast directly between `int` or `uint` and `rawptr`.

`_preload.odin(443, 28)`: either need to cast the result to `int` or `__Map_Header.value_offset` needs to be `uintptr`

`_preload.odin(464, 29)`: should just cast to `uintptr` before `u128`

**Comment by gingerBill** [comment]
With regards to the first issue, I don't want users to casts directly from a `rawptr` to a `int`/`uint` any more; they must cast to `uintptr`.

The other two seem to be bugs.

**Comment by bpunsky** [comment]
The "few issues" the first line refers to are the two issues after. `uintptr` is not a problem, it does sort of make sense. But I do think you should be able to cast any pointer type to `uintptr` directly.

**Comment by gingerBill** [comment]
It wouldn't necessarily replace `rawptr` the main reason is semantics. Any pointer can _implicitly_ cast to `rawptr` and represents a pointer rather than an integer. `uintptr` implies this is an integer but pointer size.
