### ISSUE TITLE
`write_entire_file()` doesn't truncate the old contents of the file.

### ISSUE THREAD

**Issue by shuaDev** [gingerBill/Odin#144]
```
write_entire_file("my_file.txt", "12345");
write_entire_file("my_file.txt", "abc");
```

After these two calls, the file will now read `abc45`. Not sure if this is the intended behaviour, I imagine not since this makes `write_entire_file()` almost the same as the `write_string()` proc right above it.

Fix would be to add the `O_TRUNC` flag to the call to `open()`.

**Comment by bpunsky** [comment]
I think a good solution would be to add `truncate := true` as a param, to make it a little more flexible
