### ISSUE TITLE
Cannot overload `reserve`, `append` or `len`

### ISSUE THREAD

**Issue by Tetralux** [gingerBill/Odin#148]
```odin
S :: struct(T: type)
{
	data: [dynamic]T,
}

len :: proc(s: S($T)) -> int
{
	return len(s.data);
	// Tries to call the `len` in this file, and not the one from preload.
	// My intention was for this function to be an overload, however.
}

append :: proc(s: ^S($T), item: T)
{
	append(&s.data, item);
	// Similarly for this...
}

reserve :: proc(s: ^S($T), count: int)
{
	reserve(&s.data, count);
	// And for this...
}

main :: proc() {
	s: S(int);
	n := len(s);
	reserve(&s, 5);
	append(&s, 40);
}
```

**Comment by gingerBill** [comment]
This is because those procedures are defined in the "global" scope which the file's scope is a child of. Overloading only works in the current scope. If you want to access the global scope, there is a hidden import name `_global` that you can use.

**Comment by Tetralux** [comment]
How do you use a hidden import name? Like, `using import "_global"` doesn't work.

**Comment by gingerBill** [comment]
Just use it. It should be in scope at all times available.

**Comment by Tetralux** [comment]
I'm not sure how that would help me here - this doesn't work, for instance:
```
_global.len :: proc(s: S($T)) -> int
{
    return _global.len(s.data);
}
```
I was expecting, since you can just call `len` etc without any `import`s, that I could just write a procedure with the same name and have it become an overload of the one in `_preload.odin` such that I can call both overloads in the same file without qualifying the name.

Is there no way for me to do that at the moment?

**Comment by gingerBill** [comment]
What are you doing with that declaration? A declaration's name can only be an identifier.
```
len :: proc(s: S($T)) -> int {
    return _global.len(s.data);
}
```

**Comment by Tetralux** [comment]
> What are you doing with that declaration? A declaration's name can only be an identifier.

Yeah - was guessing how I could use it. >)

The problem is that I want to be able to overload a procedure in a different scope,  so that I don't need to qualify its name every time - particularly a proc like `len` which is a fairly universal name; many types have a length, after all - would it not be better to overload `len` for their types, rather than having to call _their_ version of the `len` procedure from the scope it's defined in for the specific type their dealing with? i.e:

A.odin:
```go
S1 :: struct {}
len :: proc(s: S1) -> int { return 1; }
```
B.odin:
```go
S2 :: struct {}
len :: proc(s: S2) -> int { return 2; }
```

main.odin:
```go
using import "A.odin";
using import "B.odin";

main :: proc() {
	s1: S1;
	s2: S2;
	a := make([]int, 3);

	i := A.len(s1);
	j := B.len(s2);
	k := _global.len(a);
	// What benefit do these qualifications grant you
	// that is better than having them be overloads?
	// i.e:
	// i := len(s1);
	// j := len(s2);
	// k := len(a);

	assert(i == 1);
	assert(j == 2);
	assert(k == 3);
}
```
The same problem appears to be the case for procs in other scopes, and not just those from `_preload`.

**Comment by Tetralux** [comment]
(For clarity, they could be overloads since I `using import`'d the files, so it would make sense that they merge in that way, provided that the signatures do not collide.)

**Comment by Tetralux** [comment]
Oh - and using `_global` as a qualifier _doesn't_ actually work for `len`.
It complains that `_global` doesn't declare `len`.
