### ISSUE TITLE
Sublime Syntax Highlighting

### ISSUE THREAD

**Issue by wrongey** [gingerBill/Odin#15]
Hi Bill,

Would it be possible for you to include your sublime text syntax highlighting package?

Thank you for making this public! It's an awesome project and I look forward to working with it.

Thank you.

**Comment by thebirk** [comment]
He shares it through this gist: https://gist.github.com/gingerBill/9d9816b08fc3fd1429c558fdd90e5647

**Comment by ThisDrunkDane** [comment]
Would you be able to put it on Package Control so we can update it from there whenever you change it because of stuff like syntax changes @gingerBill?

**Comment by gingerBill** [comment]
I'll see what I can do about that. It does mean I will need to make this its own repository.
