### ISSUE TITLE
Negative integers in fmt.*

### ISSUE THREAD

**Issue by adekto** [gingerBill/Odin#21]
negative := -10;
    fmt.println(negative);

printing out negative integers  result in odd outputs
`-18446744073709551606`

**Comment by kevinend** [comment]
I opened the same issue a few days ago. Bill said that this is just a casting issue that will be fixed in the next compiler release.

**Comment by gingerBill** [comment]
See issue #19. I will close this once the new version is ready for use.

**Comment by adekto** [comment]
oh sorry dint see that anywhere
