### ISSUE TITLE
Compile-time asserts still fail even if the file is when'd out.

### ISSUE THREAD

**Issue by zangent** [gingerBill/Odin#22]
When a file is included with a 'when' statement that evaluates to false, any compile_assert is still executed. For example, take this example.
```javascript
// test.odin
#import "failure.odin" when false;
main::proc(){}

// failure.odin
_ := compile_assert(false);
```
I'll end up with `failure.odin(2:6) Compile time assertion: 'false'` even though failure.odin's asserts shouldn't have run in the first place.

Of course, this doesn't just happen with an expression that is literally 'false'.
It also happens in the standard library. When a program is compiled on any platform other than Windows, it loads os.odin, and evaluates the `compile_assert` in sys/windows.odin, even though that file isn't actually being included.

**Comment by gingerBill** [comment]
This isn't technically a bug. The compiler loads and checks __all__ files mentioned even if with those `when` conditions. If a `when` condition is true, it will import/include that file/library. This is by partially by design and by the rules I've had to create.

This will stay open as it's a little weird and this language will need a some sort of documentation.

Thank you for doing a lot of tests.

**Comment by gingerBill** [comment]
Rethinking about it, I think I'll change this 😛 and make say it is a bug.

**Comment by zangent** [comment]
I think you might've come to the same conclusion as me, but in case you didn't: the reason I said it was a bug is because it makes checks like the one on `sys/windows.odin:1` impossible to use, even though they would be nice to have. Although it would be good to be able to make sure that the compiler is only loading the win32 things on Windows, it doesn't work like that because it then makes it impossible to load `os.odin` on any other platform, since that ends up loading `sys/windows.odin`, and then the compile_assert fails.

I know multiplatform support might not be important right now, but this effectively makes most uses of compile_assert that I can see impossible.
