### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by H-225** [gingerBill/Odin#26]
- Show exactly one error in the output; don't flood the user with them.
- Improve the quality of errors in general.

e.g: Currently, using `#include` to include a file results in two messages for every
use of it:
```
C:\path\to\file\test.odin(1:2) Syntax Error: Expected `;`
C:\path\to\file\test.odin(1:1) Syntax Error: Only declarations are allowed at file scope tag statement
```
Instead, it should say something more like: `no such directive '#include'`.
And of course, bonus points for `use '#load' instead`.` ;)

**Comment by gingerBill** [comment]
This will be available in the next release.
