### ISSUE TITLE
Implicit assignment for rawptr on function pointers?

### ISSUE THREAD

**Issue by procedural** [gingerBill/Odin#36]
```C
AddProc: proc(a, b: int) -> int;
SomePtr: rawptr = nil;
AddProc = SomePtr;
```

This doesn't work without explicitly casting `SomePtr` to `proc(a, b: int) -> int`, but isn't the whole point of `rawptr` is implicit casting? I can do this in C:

```C
int (*AddProc)(int, int);
void *SomePtr = NULL;
AddProc = SomePtr;
```

And it works.

I know a cast like this is not "safe", but if I wanted safety I wouldn't use `rawptr` in the first place.

**Comment by zangent** [comment]
I could be wrong (I don't have compiler accessible right now), but I think `proc` is automatically a pointer.

This _should_ work: 
```go
AddProc: proc(a, b: int) -> int;
SomePtr: rawptr = nil;
AddProc = cast(proc(a, b: int) -> int) SomePtr;
```

This language pretty much has no implicit casting.

**Comment by procedural** [comment]
@zangent Yep, this works too, thanks!

I just hate explicit casting for raw pointers, especially in retarded C++ where a code like turns into **HELL**: https://github.com/procedural/gpulib/blob/master/gpulib.h#L234-L297

**Comment by zangent** [comment]
It doesn't have to be awful. Something like this is OK.
[gl_dynamic.odin](https://hastebin.com/isusimuvoj.hs)
[gl_win32.odin](https://hastebin.com/iyiliyewar.go)

To avoid cluttering this issue with a discussion of stylistic preference, you should probably drop your thoughts in [this programming Discord server.](https://discord.gg/awz66AN)  The author of this language is on it pretty much every day, and it's probably a better place for discussion of non-issues.

Then again, who am I to tell you where to go haha

**Comment by procedural** [comment]
```C
(cast(^(proc() #cc_c))proc_ptr)^ = ptr;
```
no thanks.

**Comment by procedural** [comment]
Temporal workaround:
```C
set_proc_rawptr :: proc(lh: rawptr, rh: rawptr) #inline {
  (cast(^(proc() #cc_c))lh)^ = transmute(proc() #cc_c)rh;
}

test := 0;
RawPtr: rawptr = ^test;

Proc1: proc(a, b: int) -> int;
Proc2: proc(a, b: int) -> int;

Proc1 = cast(proc(a, b: int) -> int)RawPtr;
set_proc_rawptr(^Proc2, RawPtr); // Same as above without explicit cast

assert(Proc1 == Proc2);
```

**Comment by ThisDrunkDane** [comment]
If you look in `opengl.odin` inside the `init :: proc()` you can see this is how he expects you (atm at least) to do that stuff.

**Comment by gingerBill** [comment]
Procedures are stored as a pointer internally which means you can convert them to and from a pointer. They are just an address (e.g. a number). It just doesn't make sense the make them a pointer as you cannot deference them like any other pointer type.

**Comment by procedural** [comment]
@gingerBill umm, it's not an answer to original question? :) (C-like implicit cast of rawptr to procedure, that is)

**Comment by procedural** [comment]
`proc_rawptr` does the job for me right now, but I just was under impression that the whole point of `rawptr` is implicit casting, otherwise what is the point of it in the first place I wonder :)

**Comment by gingerBill** [comment]
There is no implicit cast from `rawptr` to an other pointer type in Odin. It would be easy to implement but I'm not sure it is worth it. I quite the like strong type safety.

**Comment by procedural** [comment]
@gingerBill An answer I was looking for :) Thanks! The issue is closed.

**Comment by gingerBill** [comment]
Do like implicit cast of any pointer type to `rawptr` for sanity reasons. I could allow the other way too but I'd probably have to make a little poll.

**Comment by procedural** [comment]
@gingerBill Thanks! `rawptr` works too, indeed (edited the "Temporary example" from above)

```C
proc_rawptr :: proc(lh, rh: rawptr) #inline { (cast(^rawptr)lh)^ = rh; }
```
