### ISSUE TITLE
Unused return values are ignored by default?

### ISSUE THREAD

**Issue by procedural** [gingerBill/Odin#38]
```C
#import "fmt.odin";

main :: proc()
{
  using fmt;

  Func :: proc() -> int {
    return 10;
  }

  Func();

  printf("Isn't Func supposed to trigger a compile time error?\n");
  printf("And the true way of calling it would be _ := Func()?\n");
}
```

Calling `Func()` like that doesn't trigger a compile time error.

**Comment by gingerBill** [comment]
I originally made this an error/warning but I found that I was doing so often than I found it annoying.

**Comment by procedural** [comment]
Is it possible to introduce an explicit `#required_return_val`?

**Comment by gingerBill** [comment]
I don't see why not. I'll see what I can do with. Maybe have the tag be `#require_result`.

**Comment by gingerBill** [comment]
However, even with `#require_results` the results can be explicitly ignore like:
```
_ = foo();
```

**Comment by procedural** [comment]
@gingerBill Ah, result**s**, that's right, I always forget about multiple return values because of C :) Yes, ignoring it explicitly makes sense too.

**Comment by gingerBill** [comment]
I've added it `#require_results` to Odin.

**Comment by procedural** [comment]
@gingerBill Thank you! That was fast! :) Can confirm, it works, the issue is closed.
