### ISSUE TITLE
`union_cast` Syntax and Semantics

### ISSUE THREAD

**Issue by gingerBill** [gingerBill/Odin#41]
At the moment, if you want to get the variant type of a union, you will need to use either a `match in` statement or a `union_cast`. 
```
match x in y {
case TypeA:
case TypeB:
}
```
```
x := union_cast(T)y; // panics if `y` is not of type `T`
x, ok := union_cast(T)y;
```

The problem with a `union_cast` is partially its name and its use. `any` can use `match in` to get the underlying value but it cannot use `union_cast`. Should the syntax for this operation be different compared to the other types of casting (`cast` and `transmute`) to allow for `any` too?

Should the syntax be similar to Go's [type assertions](https://tour.golang.org/methods/15):
```
x := y.(T);
x, ok := y.(T);
```
or something completely different to be more _Odin-like_?

**Comment by zangent** [comment]
I don't think there's anything wrong with the current methods, although `union_cast` sounds a bit different than its actual purpose. (I understand that it _is_ a cast, but IMO that's a bit counter-intuitive to a programmer trying to pick up the language)

If it were me, I would just name it `union_subtype(u) -> u, ok` or something similar.

**Comment by procedural** [comment]
I'm with @zangent, `union_subtype` makes its purpose clearer.

**Comment by gingerBill** [comment]
`union_subtype` or `union_variant` would be good but it doesn't help with the `any` type either.

**Comment by procedural** [comment]
@gingerBill the question is about syntax, right? :) `union_subtype(u, T) -> u, ok` looks more Odin-like (or C-like) than `y.(T)`. Granted, not as short as in Go, but easier to understand than overriding the meaning of parentheses and dot notation for a special case...

**Comment by gingerBill** [comment]
It wouldn't be overriding technically. When you do a selector expression (a.b) the next token after the dot must be an identifier. So if the next token was an open parenthesis, there should be no problem.

**Comment by procedural** [comment]
Visually I associate parenthesies with function parameters and a subseequent function calls because the language doesn't use them for anything else (afaik?), adding another meaning looks to me like someone calls a funny looking function like `whatIsGoingOn.(y.(MyType).(What))` :) But maybe it's just me...

**Comment by gingerBill** [comment]
I have gone with the `x.(type)` syntax in v0.2.0 so it can support `any` as well.
