### ISSUE TITLE
Linux version doesn't link to libm for math.odin

### ISSUE THREAD

**Issue by procedural** [gingerBill/Odin#44]
I solved it by directly inserting `-lm` to this line: https://github.com/gingerBill/Odin/blob/a80872b/src/main.c#L433

**Comment by zangent** [comment]
Why does it need to?
What functions in use are a part of libm?

If you can list what _needs_ libm in compilation, then the this will be a quick fix, as the proper way to solve this is to have something like this in the offending file:
```go
#foreign_system_library libm "m";
my_libm_proc :: proc() #foreign libm;
```

**Comment by procedural** [comment]
> What functions in use are a part of libm?
`sin`, `cos`, `tan`

**Comment by gingerBill** [comment]
I'm adding it to the next commit. However, I hope to remove the explicit need for it later.

**Comment by procedural** [comment]
@gingerBill thanks!
