### ISSUE TITLE
A place to chat about Odin

### ISSUE THREAD

**Issue by bdoner** [gingerBill/Odin#45]
Hey,

I toy around, still being a beginner both at C but as well at Odin, so at times I have questions I normally would look up in the documentation. Odin by Example just doesn't cover every case yet and browsing the source here on GitHub mostly get me going but is a tedious process 😄 

So I would like to suggest there'll be an "official" IRC channel for the Odin language or possibly a Slack if you're more into that.

Personally I'm more of an IRC kind of guy but I'm open to alternatives.
If anyone's up for a small chat I'll (for now) be in `#OdinLanguage` on `freenode`.

**Comment by ratchetfreak** [comment]
there is a forum on handmade network; https://odin.handmade.network/forums and Bill can often be found in its discord

**Comment by bdoner** [comment]
There's a discord? Now look at that 😃 That's what I'm looking for I think. I can't seem to find it on odin.handmade.network, is it secret and for selected people only?

**Comment by ratchetfreak** [comment]
you'll find it on the home page of https://handmade.network/home

**Comment by gingerBill** [comment]
The discord is actually just the Handmade Network's discord. I talk a lot on there.

**Comment by bdoner** [comment]
I see you all on discord. I'll take it. Thanks!

**Comment by ThisDrunkDane** [comment]
for anyone happening upon this issue, there is a #odin on the HMN discord now
