### ISSUE TITLE
Struct with a function pointer and baked value

### ISSUE THREAD

**Issue by FelixBrendel** [gingerBill/Odin#46]
So I played around with structs and making oop style classes to see what was possible.
My minimal example code is:

```
// File: minimal.odin
#load "fmt.odin";

Human :: struct {
	toString : proc() -> string
}

CreateHuman :: proc(name : string) -> Human {
	ret : Human;
	ret.toString = proc() -> string {
		return name;
	};
	return ret;
}

main :: proc() {
	felix := CreateHuman("Felix");
	print(felix.toString(), "\n");
}
```

So I am trying to see if I can build a Java like class here with a toString method. 
When I compile I get the message: 
```
<path>\odin-v0.1.3\bin/opt: <path>\minimal.ll:3364:2: error: instruction forward referenced with type '%..string*'
        %0 = load %..string, %..string* %0, align 8
```

**Comment by gingerBill** [comment]
In this language, lambda functions are _not_ closures. They do not capture its surrounding scope. However, you have found a bug in that it should not be possible for this variable to be found.

**Comment by gingerBill** [comment]
Fixed in the latest dev version.
