### ISSUE TITLE
Weird lambda behavior

### ISSUE THREAD

**Issue by FelixBrendel** [gingerBill/Odin#48]
Ok so I freshly cloned and rebuilt the compiler now before writing this :)

I wrote a function that gets an input value and a function pointer and returns the result of the pointed function fed with the input value.

Now if I call that mapping function, with a constant function, everything is fine. When additionally called with a lambda it works too. However **just** using a lambda crashes the compiler.

```
#load "fmt.odin";

mapFunction :: proc(i: int, func: proc(int) -> string) -> string
{
	return func(i);
}

main :: proc()
{
	i : int = 4;

	f :: proc(i: int) -> string {
		return aprint(i);
	}

	// if you uncomment these lines it works
	//res1 := mapFunction(i, f);
	//print(res1, "\n");

	res2 := mapFunction(i,
			proc(i: int) -> string {
				return aprint(i);
			}
		);
	print(res2, "\n");
}
```
Also note that the lambda and constant functions are literally the same.

**Comment by gingerBill** [comment]
I know the problem for this. It is caused by the minimal dependency system not adding `aprint`. I will fix this soon.

**Comment by gingerBill** [comment]
Fixed!
