### ISSUE TITLE
Allow negative indices

### ISSUE THREAD

**Issue by procedural** [gingerBill/Odin#49]
```
Index `-1` cannot be a negative value
```
No it can :P

Since Odin doesn't have C-like pointer arithmetic, the only way to index a `rawptr` is by converting it to a slice with `slice_ptr()`, but slices don't allow negative indices.

The problem: I have a `rawptr` from some other lib that points not to the beginning, but to the middle of an array:

```
1 2 3 4
  ^
```

I need to access value `1`, but, currently, it's not possible in Odin.

**Comment by procedural** [comment]
https://github.com/gingerBill/Odin/blob/b78e970/src/exact_value.c#L569

```
// TODO(bill): Allow for pointer arithmetic? Or are pointer slices good enough?
```
Good question! :)

**Comment by procedural** [comment]
For slices, it may be a `#allow_negative_indices` tag (like `#no_bounds_check`) that disables negative indices check and bounds checking for a scope...

**Comment by gingerBill** [comment]
You can just do pointer arithmetic. That comment is old.

**Comment by procedural** [comment]
@gingerBill Cool! :D Sorry for bothering then!
