### ISSUE TITLE
How to disable mangling for bss variables?

### ISSUE THREAD

**Issue by ghost** [gingerBill/Odin#52]
I want to share some global variables with C code, but Odin mangles them with a file name and some number. I can tag a function with `#link_name` and specify the exact linking name I need, can I do the same for global variables? Thanks!

**Comment by procedural** [comment]
Current ugly workaround: wrapping function pointers in standard functions :package: https://github.com/procedural/gpulib/blob/f6f71e2/gpulib.odin#L72-L137
I imagine for other variables I need to wrap them in get / set functions...

**Comment by gingerBill** [comment]
Odin does allow importing #foreign global variables yet, nor does it have the ability to export them. 

This may sound daft, but a problem with it is the syntax. `#foreign lib_name `on procedures looks okay but how would you apply that to a global variable? What would be its corresponding syntax?

**Comment by procedural** [comment]
How about `#extern_export`, `#extern_import` before a variable's name?

**Comment by gingerBill** [comment]
That works for exporting but not for importing. For procedures, you need to specify the library it comes from. How would the syntax look for that?

**Comment by procedural** [comment]
Oh, right, how about:
```
var_out: i32 #extern_export;
var_in: bool #extern_import_from myForeignLib;
```
?
