### ISSUE TITLE
Short if as parameter

### ISSUE THREAD

**Issue by FelixBrendel** [gingerBill/Odin#60]
Is this a bug?
```
println(i % 3 == 0 ? "Fizz" : i);
// <file>.odin(7:24) Cannot convert `Fizz` to `int`
```

**Comment by bdoner** [comment]
I think it is evaluated as following  `println((i % 3) == (0 ? "Fizz" : i));`

If it's a bug?  That depend on bill's intentions ;)

**Comment by ratchetfreak** [comment]
there are no implicit conversions from int to string so there is no reasonable behavior that can be compiled from that. So even println((i % 3 == 0) ? "Fizz" : i); shouldn't compile.

What I think it happening is that the type of a conditional is the else part and the then part should match it.

**Comment by H-225** [comment]
@ratchetfreak
>  there is no reasonable behavior that can be compiled from that

One way to fix this would be to make the return type of a ternary `any` if the branches have different types. Seems pretty reasonable to me...

**Comment by FelixBrendel** [comment]
Why change the bavaviour of the ternary operator? Print can take ints and strings as parameters already?

**Comment by ratchetfreak** [comment]
@FelixBrendel that's not how it's compiled

`println((i % 3 == 0) ? "Fizz" : i);` is compiled as

```
_t := (i % 3 == 0) ? "Fizz" : i;
println(_t);
```

So what type should `_t` get? That decides which overload of `println` gets called. Making it `any` would frankly overcomplicate the ternary operator and code surrounding it while it's already not the best thing around.

So an error when the types in the cases of the ternary don't match is a good thing™.

**Comment by gingerBill** [comment]
Odin has a strict type system. This means the expression `cond ? a : b` is evaluated like so:
* `cond` must be a boolean type
* The type of `a` must be assignable to `b` and/or `b` must be assignable to `a`

A ternary condition expression must have a known concrete type at compile time; it cannot be multiple types in the case you are presenting.

The expression doesn't care that much where it's going, it's evaluated there and then. Once that expression is evaluated, it will see if it can be implicitly converted to the procedure parameter (in this case an `any`). And thus, it does check if each component of the ternary can be converted rather the bulk expression.

**Comment by gingerBill** [comment]
Side note: Theoretically, if the condition is a constant (know at compile time), it could be possible to have different types but I think that it just daft.
