### ISSUE TITLE
Possible bug using "using". 

### ISSUE THREAD

**Issue by vassvik** [gingerBill/Odin#62]
In the following code: https://github.com/vassvik/odin-glfw/blob/master/main.odin#L105
the program segfaults (error code -11). 

Adding "io." to any of the struct variables below the comments makes it *not* segfault. 

This is in linux, latest commit.

**Comment by vassvik** [comment]
To clarify: the compiler segfaults, not the compiled program.

**Comment by gingerBill** [comment]
Does this segfault happen on Windows too or is it just Linux?

**Comment by vassvik** [comment]
I don't have access to a Windows machine for a while, so I would need someone else to test (just pull that repo and run main.odin should do).

Here's the log from gdb:
`Program received signal SIGSEGV, Segmentation fault.
ir_build_addr (proc=0x7fffebe9a180, expr=0x0) at src/ir.c:4746
4746		switch (expr->kind) {
`

"expr" is NULL.

**Comment by gingerBill** [comment]
I forgot to add the entity's use and associate that identifier with it.
