### ISSUE TITLE
Unable to compile on mac

### ISSUE THREAD

**Issue by brokenbeta** [gingerBill/Odin#65]
I'm getting the following error when I try to compile Odin on an El Capitan Macbook:

    In file included from src/main.c:8:
    src/timings.c:37:2: warning: implicit declaration of function 'clock_gettime' is invalid in C99
          [-Wimplicit-function-declaration]
            clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &ts);
            ^
    src/timings.c:37:16: error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
            clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &ts);
                          ^
    src/timings.c:47:3: warning: implicit declaration of function 'clock_getres' is invalid in C99
          [-Wimplicit-function-declaration]
                    clock_getres(CLOCK_PROCESS_CPUTIME_ID, &ts);
                    ^
    src/timings.c:47:16: error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
                    clock_getres(CLOCK_PROCESS_CPUTIME_ID, &ts);
                                 ^
    In file included from src/main.c:9:
    src/build_settings.c:116:7: warning: incompatible pointer types assigning to 'wchar_t *' (aka 'int *') from
          'u8 *' (aka 'unsigned char *') [-Wincompatible-pointer-types]
            text = gb_alloc_array(string_buffer_allocator, u8, len + 1);
                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/build_settings.c:119:21: warning: incompatible pointer types passing 'wchar_t *' (aka 'int *') to
          parameter of type 'u8 *' (aka 'unsigned char *') [-Wincompatible-pointer-types]
            path = make_string(text, len);
                               ^~~~
    src/string.c:29:34: note: passing argument to parameter 'text' here
    gb_inline String make_string(u8 *text, isize len) {
                                     ^
    4 warnings and 2 errors generated.
    ./build.sh: line 24: ./odin: No such file or directory

I have a separate build of llvm 3.8 installed on my machine and I did also try changing build.sh to use that instead of Apple's llvm but it didn't seem to change anything.

**Comment by clankill3r** [comment]
I have the same error. I think I have llvm configured wrong.
Also when I do `echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile` for example. And then `echo $PATH` it shows not up.
Setting paths on OSX is pure cancer.

**Comment by clankill3r** [comment]
@brokenbeta I'm a lot of steps further now.

-You need `OSX Sierra (10.12)` cause prior to 10.12 `clock_gettime` and `clock_getres` and `CLOCK_PROCESS_CPUTIME_ID` etc. does not exist.
-After updating make sure to update Xcode.
-Update the command line tools

@gingerBill When I run the `build.sh` now I get the following output:

```
/Users/doekewartena/Documents/Odin/core/opengl.odin(11:6) Compile time assertion: `ODIN_OS != osx`
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(13:9) Undeclared name: lib
/Users/doekewartena/Documents/Odin/core/opengl.odin(44:11) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(8:26) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(9:26) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(10:26) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(11:26) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(21:9) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(24:9) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(27:9) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(31:9) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(34:9) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(66:9) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(69:9) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(72:9) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(75:9) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/atomics.odin(78:9) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/opengl.odin(52:9) Undeclared name: wgl
/Users/doekewartena/Documents/Odin/core/opengl.odin(54:9) Undeclared name: win32
/Users/doekewartena/Documents/Odin/core/opengl.odin(54:3) Assignment count mismatch `1` = `0`
/Users/doekewartena/Documents/Odin/core/os_x.odin(204:9) Cannot assign value `size` of type `int` to `i64` in return statement
```

**Comment by brokenbeta** [comment]
I've had no issues compiling on mac anymore, so you might be able to close this now.

**Comment by barracuda156** [comment]
> Why was this issue resurrected?! @barracuda156

I ran into an error with undefined `CLOCK_PROCESS_CPUTIME_ID` when building `folly`: https://github.com/macports/macports-ports/pull/15689
So been looking for a suitable fix.

**Comment by gingerBill** [comment]
On a 5 year old closed Odin compiler issue where your unrelated bug is for a C++ project?

**Comment by Kelimion** [comment]
You're missing the point that you're telling someone who had an issue 5 years ago, which was resolved soon thereafter, how *not* to fix that issue he hasn't had for years.

So not only was your comment unhelpful now, it would've been unhelpful then, and you've just wasted - in aggregate among the number of people who are notified of and read issues - several thousand minutes of people's time, because you thought it would be helpful to let people know that `CLOCK_PROCESS_CPUTIME_ID` is used in more than 1 project on the internet.

Kindly stop helping people at it in the future.
