### ISSUE TITLE
Flags for os.open do not work

### ISSUE THREAD

**Issue by FelixBrendel** [gingerBill/Odin#75]
The Flags in 
`os.open(fileHandle, O_APPEND | O_CREAT);` 
do not work, especially the ones for append and create. The file seems to get opened the same way regardless of the flags and the content gets overwritten.

**Comment by gingerBill** [comment]
Could you please specify which operating system.

**Comment by FelixBrendel** [comment]
Sorry, forgot to mention. This happened on Windows 10.

**Comment by bdoner** [comment]
I just tested following code on Windows 10 with `odin version 0.6.0-dev`

```
import "os.odin";

main :: proc() {
	appendToFile();
	appendToFile();
}

appendToFile :: proc() {
	handle, s := os.open("testfile.txt", os.O_CREAT | os.O_APPEND);
	if s != os.ERROR_NONE {
		panic("Could not open file.");
	}

	os.write(handle, []u8("wup wup\r\n"));
	os.close(handle);
}
```

which correctly created a file, `testfile.txt`, containing two lines; 
```
wup wup
wup wup
```

Do you have a code that can reproduce the bug?

**Comment by FelixBrendel** [comment]
Your code works, I tracked down the issue to possibly another bug related to `if .. do`. I will close the issue. Thanks for your help! :)
