### ISSUE TITLE
__get_map_header bug

### ISSUE THREAD

**Issue by bpunsky** [gingerBill/Odin#78]
E:\Workspace\Odin\core\_preload.odin(420:18) Type assertions can only operate on unions and `any`
E:\Workspace\Odin\core\_preload.odin(421:9) Assignment count mismatch `1` = `0`
E:\Workspace\Odin\core\_preload.odin(432:13) Invalid type for this type match expression, got `^TypeInfo`

Not 100% on what I'm doing that calls this - just assigning to a map, I assume.

**Comment by gingerBill** [comment]
Fixed.
