### ISSUE TITLE
Mysterious problem with any

### ISSUE THREAD

**Issue by bpunsky** [gingerBill/Odin#79]
Not sure what to make of this. I was having trouble with a much more complex piece of code, thinking it was a bug on my side. When I realized it was a problem with Odin, I managed to distill it down to this.

The problem only seems to occur when using any - if I use an array of strings, this works fine. The code below will crash. If you comment the return and uncomment the one above it, you will get much stranger behavior (the last value printed four times). If you don't use a function, and instead do it all inline in the main procedure, it will work fine. If you make the function inline, it still doesn't work.

```
main :: proc() {
    foos: [dynamic]any;

    add :: proc(foos: ^[dynamic]any, foo: string) -> ^string {
        append(foos, foo);
        //return cast(^string)foos[len(foos)-1].data;
        return nil;
    }

    add(&foos, "A B C D");
    add(&foos, "1 2 4 3");
    add(&foos, "Apple Tree Bird Bee");
    add(&foos, "Coffee Milk Juice Tea");

    for foo in foos {
        fmt.println(foo);
    }
}
```

**Comment by gingerBill** [comment]
This is not technically a compiler bug.

The `foo` in `add` is allocated on the stack and when converted to an any, its stack address is used for the `data` field. When this stack frame is not valid any more, this is causing the problem. To solve this issue, you could either change `foo: string` to `foo: any` or allocate the data needed to ensure that the lifetime of the variable exceeds that stack frame.

**Comment by bpunsky** [comment]
Is there any method to ensure that any any is dynamically allocated rather than locally? If not, is this in the plans? For now I guess I'll create a procedure that takes an any and returns a dynamically allocated any - and kudos to you and Odin for making that a trivial thing to do!

**Comment by gingerBill** [comment]
The best way to it do something like this:
```
append(&foos, new_clone(foo_bar)^);
```
That will allocate a new type and copy the original.

**Comment by bpunsky** [comment]
The only problem is that the any would then be of type ^T rather than T, which doesn't work for my purposes (it's also another level of indirection).

This is what I came up with:

new_any :: proc(x: any) -> any {
    raw_any := raw.Any {
        data      = alloc(x.type_info.size, x.type_info.align),
        type_info = any.type_info, 
    };

    mem.copy(raw_any.data, x.data, x.type_info.size);

    return cast(any)raw_any;
}

By the way, are strings allocated on the stack or heap?

**Comment by bpunsky** [comment]
Works great, thanks!
