### ISSUE TITLE
Compiler can't handle spaces in project directory

### ISSUE THREAD

**Issue by JonBoyleCoding** [gingerBill/Odin#8]
I just downloaded and compiled Odin (congratulations on having a simple Windows compilation process!) and came across a bug with your compiler.

![image](https://cloud.githubusercontent.com/assets/630329/22121389/c6b6a900-de7b-11e6-8729-02db3e940e89.png)

The code is just a simple Hello World program as follows and compiles (did you re-add the need for ; at end of statements after your November stream? Haven't watched this months one yet).

> #import "fmt.odin";
> 
> main :: proc() {
> 	fmt.println("Hello World!");
> }

I'm presuming that when you call the opt.exe that you don't consider the current directory could be one with spaces in it. I plan on having a look at the code myself, but in case you happen to see this before I have a chance to or know exactly where to look...

(I don't normally have spaces in directory names being a Linux guy, but when on Windows I have a hard time not using them)

**Comment by gingerBill** [comment]
This is now fixed.
