### ISSUE TITLE
__get_map_key issue

### ISSUE THREAD

**Issue by bpunsky** [gingerBill/Odin#80]
E:\Workspace\Odin\core\_preload.odin(433:13) Invalid type for this type match expression, got `^TypeInfo`

It seems like the problem is that you are iterating the language and core types so fast that it's difficult to keep up with the code breaking. It would be extremely useful to have a compiler flag to force the compiler to check even procedures that won't be called for warnings and errors; I've had the same thing happen to me, not fixing broken code because it wasn't being compiled. Such a flag would let you and your users clean up broken code after making changes with a lot of downstream effects.

**Comment by gingerBill** [comment]
The procedure that don't get checked are polymorphic procedures. I need to figure out a way to check to "unspecialized" polymorphic procedure's body.

In this case, I think I have fixed the case before I read this issue.

**Comment by bpunsky** [comment]
Interesting, and that makes sense. I can see how that would be problematic, but would it not be possible to check for simpler things such as undeclared identifiers? Theoretically checking the parts of the code that aren't touched by the polymorphic types would be doable, but I have to admit I can see how they could have a cascade effect making the whole thing pretty messy.
