### ISSUE TITLE
`[dynamic]T` literals crash the compiler

### ISSUE THREAD

**Issue by H-225** [gingerBill/Odin#86]
Crashes the compiler:
```
import_load "fmt.odin";

main :: proc() {
    x := [dynamic]int{1};
    println(x);
}
```

Works as expected:
```
import_load "fmt.odin";

main :: proc() {
    x := []int{1};
    println(x);
}
```

**Comment by gingerBill** [comment]
What OS are you compiling on? This does not crash Windows.

**Comment by H-225** [comment]
I am on a almost-fresh install of Windows 10 x64, build 15063.
I am using Visual Studio 2017 and called the native x64 vcvars.bat before invoking either `odin.exe` or `build.bat`. i.e: the one located at: `\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat`.

The following program crashes after several seconds of being invoked:
```
import_load "fmt.odin";

main :: proc() {
    x := [dynamic]int{1};
    println(x);
}
```

**Comment by H-225** [comment]
At `ir_print.cpp:34".
This is the error message:
```
Unhandled exception at 0x00007FF781CB49C0 in odin.exe: 0xC0000005: Access violation writing location 0x000001CB21EA8000. occurred
```
The watch window says `len` is `-2`.

**Comment by H-225** [comment]
Seems that `ir_get_global_name` returns a string of text `_` with length `-2`.
It has no filename or line number, however.

**Comment by H-225** [comment]
It further seems that the `value` (entity ID 4613) passed to `ir_print_value` is a global, who's `.entity.token.string` is already erroneous when it passed in.
