### ISSUE TITLE
A lot of new issues when compiling on mac

### ISSUE THREAD

**Issue by clankill3r** [gingerBill/Odin#88]
Before I was almost able to get Odin to compile on a mac.
If I removed `import opengl.odin` and `import atomics.odin` then I was only left with:

> /Users/doekewartena/Documents/Odin/core/os_x.odin(204:9) Cannot assign value 'size' of type 'int' to 'i64' in return statement

Which I think is a bug in Odin where a cast is forgotten.

However, I tried to build again (build.sh) and this is the output I have now:

> 
> In file included from src/main.cpp:7:
> In file included from src/common.cpp:7:
> src/gb/gb.h:7995:9: error: use of undeclared identifier 'remove'; did you mean 'revoke'?
>         return remove(filename) == 0;
>                ^~~~~~
>                revoke
> /usr/include/unistd.h:694:6: note: 'revoke' declared here
> int      revoke(const char *);
>          ^
> In file included from src/main.cpp:11:
> src/parser.cpp:4762:33: error: call to 'next_pow2' is ambiguous
>                 isize init_token_cap = gb_max(next_pow2(file_size/2), 16);
>                                               ^~~~~~~~~
> src/gb/gb.h:699:24: note: expanded from macro 'gb_max'
> #define gb_max(a, b) ((a) > (b) ? (a) : (b))
>                        ^
> src/common.cpp:271:5: note: candidate function
> i32 next_pow2(i32 n) {
>     ^
> src/common.cpp:284:5: note: candidate function
> i64 next_pow2(i64 n) {
>     ^
> In file included from src/main.cpp:11:
> src/parser.cpp:4762:33: error: call to 'next_pow2' is ambiguous
>                 isize init_token_cap = gb_max(next_pow2(file_size/2), 16);
>                                               ^~~~~~~~~
> src/gb/gb.h:699:36: note: expanded from macro 'gb_max'
> #define gb_max(a, b) ((a) > (b) ? (a) : (b))
>                                    ^
> src/common.cpp:271:5: note: candidate function
> i32 next_pow2(i32 n) {
>     ^
> src/common.cpp:284:5: note: candidate function
> i64 next_pow2(i64 n) {
>     ^
> In file included from src/main.cpp:15:
> src/ir.cpp:3606:4: warning: format specifies type 'unsigned int' but the argument has type 'isize' (aka 'long')
>       [-Wformat]
>                         file->id,
>                         ^~~~~~~~
> 1 warning and 3 errors generated.
> ./build.sh: line 24: ./odin: No such file or directory

**Comment by gingerBill** [comment]
How about now?

**Comment by stevetranby** [comment]
Another issue is `existing_filename` should be `filename`
```
// Line ~7994
b32 gb_file_remove(char const *filename) {
#if defined(GB_SYSTEM_OSX)
        return unlink(existing_filename) != -1;
#else
        return remove(filename) == 0;
#endif
}
```

**Comment by stevetranby** [comment]
Then need to either cast `offset` to int (or change the parameter in FFI decl to int64) 
```
final_offset := i64(unix_lseek(fd, int(offset), whence));
```

Reminder if you have recently installed XCode
```
# assuming `brew install llvm`
export PATH="/usr/local/opt/llvm/bin:$PATH"
./build.sh
```

After this latest github master compiled for me.

**Comment by clankill3r** [comment]
With the 2 suggested changes from @stevetranby it works now!
Both thanks.

**Comment by gingerBill** [comment]
It should be fixed now in the latest commit. So for the blind changes.
