### ISSUE TITLE
Sublime Build Settings / Syntax Highlighting

### ISSUE THREAD

**Issue by JonBoyleCoding** [gingerBill/Odin#9]
Do you have/are you planning on uploading your sublime build settings/syntax highlighting at all?

Edit: Just to note, I'm just playing around with Odin for fun, not planning on doing any serious coding at the moment (trying a few 'simple' programs)

**Comment by gingerBill** [comment]
This is what I currently use: https://gist.github.com/gingerBill/9d9816b08fc3fd1429c558fdd90e5647

**Comment by gingerBill** [comment]
This what I use for building with a `build.bat` file:
```json
{
	"shell_cmd": "build.bat",
	"file_regex": "^ *([A-z]:.*)[(]([0-9]+)([:][0-9]+)*[)]",
	"working_dir": "${project_path:${folder}}"
}
```
This will work with MSVC and Odin.
