### ISSUE TITLE
"import ." on a file with an "import_load" in it

### ISSUE THREAD

**Issue by shuaDev** [gingerBill/Odin#90]
```
// foo.odin
import . "bar.odin";

main :: proc() {
    baz_proc();
}

// bar.odin
import_load "baz.odin";

// baz.odin
baz_proc :: proc() { }
```

I feel like something like this should work. My use case was I wanted to make an `sd_fmt.odin` that does an `import_load "fmt.odin";` and then I'd add my own `fmt` style procs to `sd_fmt.odin` and then in my code I could `import . "sd_fmt.odin";` and have easy access to both my procs and the ones in `fmt.odin`. This seems like a really neat way to extend the standard lib by leveraging the features of the language without changing any actual code on the user side, just imports.

Note that this DOES work:

```
// foo.odin
import "bar.odin";

main :: proc() {
    bar.baz_proc();
}

// bar.odin
import_load "baz.odin";

// baz.odin
baz_proc :: proc() { }
```

it's just that if you want to use `import .` that it doesn't

**Comment by gingerBill** [comment]
The import system is still in development and the main goal for the next release. These problems will be resolved with by fixing them or removing them entirely. This is because we need to decide on what the library system is.
