### ISSUE TITLE
casting ptr to int

### ISSUE THREAD

**Issue by bpunsky** [gingerBill/Odin#92]
`transmute(int) ^foo;`

> C:\odin\bin/opt: E:\Workspace\odin-stuffs\test.ll:17986:17: error: invalid cast opcode for cast from '%..string*' to 'i64'
>    %122 = bitcast %..string* %121 to i64

**Comment by gingerBill** [comment]
I will fix this tonight but casting between an `int`/`uint` and a pointer should be no problem using `cast` rather than `transmute`.
