### ISSUE TITLE
`export` doesn't seem to respect `when` condition

### ISSUE THREAD

**Issue by terickson001** [gingerBill/Odin#93]
Building on GNU/Linux, it seems that `core:sys/windows.odin` is imported when ODIN_OS != "windows", which causes the compiler to throw an `undeclared name` error for every `foreign_system_library` declared in `core:sys/windows.odin`.

From what I can tell it seems that `core:os_windows` must always be exported from `core:os.odin` regardless of the value of `ODIN_OS`. I would assume this doesn't raise an error on Windows because there are no `when` conditions on the `foreign_system_library` declarations in `core:os_linux.odin` or `core:os_x.odin`.

**Comment by vassvik** [comment]
It seems to be related to the import of `os_windows.odin` file being exported regardless of whether the `when` statement evaluates against "windows" is true or not. The "osx" works fine. Adding the `when` condition checking against "windows" on the foreign imports in `os_linux.odin` works as expected, which is weirder. 

A temporary fix on linux is to simply comment/remove the line that says `export "core:os_windows.odin" when ODIN_OS == "windows";` in `os.odin`.

**Comment by gingerBill** [comment]
This bug has happened before but I have absolutely no idea as to how it got fixed last time.
